-- 1. counsels 테이블 생성 쿼리문
-- Supabase SQL Editor에 그대로 복사해서 붙여넣으시면 됩니다.

CREATE TABLE IF NOT EXISTS counsels (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  student_name TEXT NOT NULL,
  content TEXT NOT NULL
);

-- (선택사항) 익명 게시판이므로 누구나 조회 및 추가할 수 있도록 RLS(행 보안 정책) 설정
ALTER TABLE counsels ENABLE ROW LEVEL SECURITY;

CREATE POLICY "누구나 조회 가능" ON counsels 
  FOR SELECT USING (true);

CREATE POLICY "누구나 작성 가능" ON counsels 
  FOR INSERT WITH CHECK (true);

-- 2. 테스트용 1건 가짜 데이터 삽입 쿼리문
INSERT INTO counsels (student_name, content)
VALUES (
  '익명의 금쪽이', 
  '선생님, 요즘 공부도 어렵고 짝꿍이랑 사소한 오해로 다퉜는데 어떻게 화해해야 할지 모르겠어서 밤마다 잠이 안 와요...'
);
